### ISSUE TITLE
为什么最新版的库的字段是可选

### ISSUE THREAD

**Issue by Lenny9789** [netyouli/SexyJson#1]
师傅啊， 之前的版本不都是强制解包吗， 现在为什么模型里面的字段都是变成可选了， 这样的话， 每次写代码都要强制解包，又要出问题啊，怎么办

**Comment by Lenny9789** [comment]
师傅，。。。。

**Comment by netyouli** [comment]
因为如果值为nil强制猎豹就会崩溃
