### ISSUE TITLE
升级Xcode10,swift4.2之后

### ISSUE THREAD

**Issue by Ruanjijian** [netyouli/SexyJson#2]
<img width="325" alt="2018-09-21 5 07 19" src="https://user-images.githubusercontent.com/12793624/45871902-2f9dab00-bdc1-11e8-9266-6915d0807a53.png">
<img width="890" alt="2018-09-21 5 09 03" src="https://user-images.githubusercontent.com/12793624/45871867-1137af80-bdc1-11e8-8be9-1bea5bfda98c.png">
<img width="920" alt="2018-09-21 5 09 42" src="https://user-images.githubusercontent.com/12793624/45871906-31676e80-bdc1-11e8-806d-329272c7c8de.png">

**Comment by netyouli** [comment]
这周会进行升级修复

**Comment by netyouli** [comment]
已经修复解决
